import React, { useState } from 'react';
import { Layers, MapPin, CheckCircle, AlertTriangle, ArrowRight, ShieldCheck, RefreshCw, GitMerge, FileSpreadsheet } from 'lucide-react';

const DuplicateAnalyzer = () => {
  const [analyzing, setAnalyzing] = useState(false);
  const [selectedCluster, setSelectedCluster] = useState(null);

  // Mocked duplicate cluster data generated by geospatial 50m proximity + AI visual hash matching
  const duplicateClusters = [
    {
      clusterId: 'CLUSTER-THJ-104',
      locationName: 'Old Bus Stand Junction, Thanjavur',
      coordinates: [79.1378, 10.7869],
      primaryIssue: 'Severe Pothole #1',
      severity: 'High',
      reportsCount: 8,
      distanceRadius: '14 meters',
      firstReported: '2026-10-02 09:14 AM',
      lastReported: '2026-10-08 06:45 AM',
      reports: [
        { id: 'REP-1001', citizen: 'Karthik S.', time: '2026-10-02 09:14 AM', confidence: 0.96, status: 'Master Record' },
        { id: 'REP-1042', citizen: 'Priya R.', time: '2026-10-03 11:20 AM', confidence: 0.94, status: 'Linked Duplicate' },
        { id: 'REP-1088', citizen: 'Anand M.', time: '2026-10-05 02:15 PM', confidence: 0.91, status: 'Linked Duplicate' },
        { id: 'REP-1104', citizen: 'Devi K.', time: '2026-10-08 06:45 AM', confidence: 0.95, status: 'Linked Duplicate' },
      ]
    },
    {
      clusterId: 'CLUSTER-THJ-209',
      locationName: 'Near Royal Palace Museum Gate',
      coordinates: [79.1450, 10.7920],
      primaryIssue: 'Overflowing Garbage Bin #3',
      severity: 'Medium',
      reportsCount: 5,
      distanceRadius: '8 meters',
      firstReported: '2026-10-04 08:30 AM',
      lastReported: '2026-10-07 04:10 PM',
      reports: [
        { id: 'REP-2003', citizen: 'Suresh V.', time: '2026-10-04 08:30 AM', confidence: 0.89, status: 'Master Record' },
        { id: 'REP-2055', citizen: 'Meena P.', time: '2026-10-06 01:05 PM', confidence: 0.87, status: 'Linked Duplicate' },
        { id: 'REP-2091', citizen: 'Ravi Kumar', time: '2026-10-07 04:10 PM', confidence: 0.92, status: 'Linked Duplicate' }
      ]
    },
    {
      clusterId: 'CLUSTER-THJ-312',
      locationName: 'Medical College Road, Sector 4',
      coordinates: [79.1400, 10.7780],
      primaryIssue: 'Water Main Pipe Leak #7',
      severity: 'High',
      reportsCount: 12,
      distanceRadius: '22 meters',
      firstReported: '2026-10-06 07:00 AM',
      lastReported: '2026-10-08 07:10 AM',
      reports: [
        { id: 'REP-3001', citizen: 'Dr. Ramesh', time: '2026-10-06 07:00 AM', confidence: 0.98, status: 'Master Record' },
        { id: 'REP-3044', citizen: 'Lakshmi N.', time: '2026-10-06 09:45 AM', confidence: 0.95, status: 'Linked Duplicate' },
        { id: 'REP-3112', citizen: 'Ganesh T.', time: '2026-10-08 07:10 AM', confidence: 0.94, status: 'Linked Duplicate' }
      ]
    }
  ];

  const handleRunAnalysis = () => {
    setAnalyzing(true);
    setTimeout(() => {
      setAnalyzing(false);
    }, 1200);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* Session Banner */}
      <div className="glass-panel" style={{ padding: '24px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h2 style={{ margin: '0 0 6px 0', fontSize: '22px', fontWeight: '700', display: 'flex', alignItems: 'center', gap: '10px' }}>
            <Layers size={24} style={{ color: 'var(--accent-color)' }} />
            Geospatial Duplicate Intelligence Session
          </h2>
          <p style={{ margin: 0, color: 'var(--text-muted)', fontSize: '14px' }}>
            AI-driven spatial clustering (Haversine 50m radius) and SSIM perceptual hashing prevent duplicate worker assignments.
          </p>
        </div>
        <div style={{ display: 'flex', gap: '12px' }}>
          <button className="btn-secondary" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <FileSpreadsheet size={16} /> Export Cluster Matrix
          </button>
          <button 
            className="btn-primary" 
            onClick={handleRunAnalysis} 
            disabled={analyzing}
            style={{ display: 'flex', alignItems: 'center', gap: '8px' }}
          >
            <RefreshCw size={16} className={analyzing ? 'spin' : ''} />
            {analyzing ? 'Scanning DB...' : 'Run Duplicate Scan'}
          </button>
        </div>
      </div>

      {/* Metrics Row */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '16px' }}>
        <div className="glass-panel" style={{ padding: '20px' }}>
          <div style={{ fontSize: '12px', textTransform: 'uppercase', color: 'var(--text-muted)', fontWeight: '600' }}>
            Total Analyzed Reports
          </div>
          <div style={{ fontSize: '28px', fontWeight: '700', marginTop: '8px' }}>100</div>
          <div style={{ fontSize: '12px', color: '#10b981', marginTop: '4px' }}>100% Coverage (Thanjavur)</div>
        </div>

        <div className="glass-panel" style={{ padding: '20px' }}>
          <div style={{ fontSize: '12px', textTransform: 'uppercase', color: 'var(--text-muted)', fontWeight: '600' }}>
            Clustered Duplicate Groups
          </div>
          <div style={{ fontSize: '28px', fontWeight: '700', marginTop: '8px', color: '#eab308' }}>25 Clusters</div>
          <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '4px' }}>Avg 4 reports per cluster</div>
        </div>

        <div className="glass-panel" style={{ padding: '20px' }}>
          <div style={{ fontSize: '12px', textTransform: 'uppercase', color: 'var(--text-muted)', fontWeight: '600' }}>
            Worker Hours Saved
          </div>
          <div style={{ fontSize: '28px', fontWeight: '700', marginTop: '8px', color: '#10b981' }}>180+ Hours</div>
          <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '4px' }}>Prevented redundant dispatch</div>
        </div>

        <div className="glass-panel" style={{ padding: '20px' }}>
          <div style={{ fontSize: '12px', textTransform: 'uppercase', color: 'var(--text-muted)', fontWeight: '600' }}>
            Deduplication Accuracy
          </div>
          <div style={{ fontSize: '28px', fontWeight: '700', marginTop: '8px', color: 'var(--accent-color)' }}>97.8%</div>
          <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '4px' }}>Verified by SSIM & GIS</div>
        </div>
      </div>

      {/* Cluster Table and Details View */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 340px', gap: '20px' }}>
        {/* Active Clusters list */}
        <div className="glass-panel" style={{ padding: '20px' }}>
          <h3 style={{ margin: '0 0 16px 0', fontSize: '16px', fontWeight: '600' }}>
            Detected High-Density Duplicate Clusters
          </h3>
          <table className="admin-table">
            <thead>
              <tr>
                <th>Cluster ID</th>
                <th>Location / Landmark</th>
                <th>Primary Issue</th>
                <th>Duplicates</th>
                <th>Radius</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {duplicateClusters.map((cluster) => (
                <tr 
                  key={cluster.clusterId} 
                  style={{ cursor: 'pointer', background: selectedCluster?.clusterId === cluster.clusterId ? 'rgba(249, 115, 22, 0.1)' : 'transparent' }}
                  onClick={() => setSelectedCluster(cluster)}
                >
                  <td><strong>{cluster.clusterId}</strong></td>
                  <td>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                      <MapPin size={14} style={{ color: 'var(--accent-color)' }} />
                      {cluster.locationName}
                    </div>
                  </td>
                  <td>{cluster.primaryIssue}</td>
                  <td>
                    <span style={{ background: '#eab30822', color: '#eab308', padding: '3px 8px', borderRadius: '12px', fontWeight: '700', fontSize: '12px' }}>
                      {cluster.reportsCount} Reports
                    </span>
                  </td>
                  <td>{cluster.distanceRadius}</td>
                  <td>
                    <button className="btn-secondary" style={{ padding: '4px 10px', fontSize: '12px' }}>
                      Inspect <ArrowRight size={12} style={{ marginLeft: '4px' }} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Selected Cluster Inspection Panel */}
        <div className="glass-panel" style={{ padding: '20px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <h3 style={{ margin: 0, fontSize: '16px', fontWeight: '600', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <GitMerge size={18} style={{ color: 'var(--accent-color)' }} />
            Cluster Deep Dive
          </h3>

          {selectedCluster ? (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', fontSize: '13px' }}>
              <div style={{ background: 'rgba(255,255,255,0.03)', padding: '12px', borderRadius: '10px', border: '1px solid var(--border-color)' }}>
                <div style={{ fontWeight: '700', fontSize: '14px', color: 'var(--text-main)' }}>{selectedCluster.primaryIssue}</div>
                <div style={{ color: 'var(--text-muted)', marginTop: '4px' }}>{selectedCluster.locationName}</div>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '8px', fontSize: '12px' }}>
                  <span>First: {selectedCluster.firstReported}</span>
                  <span>Latest: {selectedCluster.lastReported}</span>
                </div>
              </div>

              <div>
                <strong style={{ display: 'block', marginBottom: '8px', color: 'var(--text-main)' }}>Linked Citizen Reports ({selectedCluster.reports.length})</strong>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                  {selectedCluster.reports.map((rep) => (
                    <div 
                      key={rep.id} 
                      style={{ 
                        padding: '10px', 
                        borderRadius: '8px', 
                        background: rep.status === 'Master Record' ? 'rgba(16, 185, 129, 0.1)' : 'rgba(255,255,255,0.03)',
                        border: rep.status === 'Master Record' ? '1px solid #10b981' : '1px solid var(--border-color)',
                        display: 'flex',
                        justify: 'space-between',
                        alignItems: 'center'
                      }}
                    >
                      <div>
                        <div style={{ fontWeight: '600', color: 'var(--text-main)' }}>{rep.id} - {rep.citizen}</div>
                        <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>{rep.time} • Confidence: {(rep.confidence * 100).toFixed(0)}%</div>
                      </div>
                      {rep.status === 'Master Record' ? (
                        <span style={{ fontSize: '10px', background: '#10b981', color: 'white', padding: '2px 6px', borderRadius: '4px', fontWeight: '700' }}>MASTER</span>
                      ) : (
                        <span style={{ fontSize: '10px', background: 'rgba(255,255,255,0.1)', color: 'var(--text-muted)', padding: '2px 6px', borderRadius: '4px' }}>DUPLICATE</span>
                      )}
                    </div>
                  ))}
                </div>
              </div>

              <button className="btn-primary" style={{ marginTop: '10px', width: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center', gap: '8px' }}>
                <ShieldCheck size={16} /> Auto-Merge Selected Duplicates
              </button>
            </div>
          ) : (
            <div style={{ textAlign: 'center', padding: '40px 10px', color: 'var(--text-muted)', fontSize: '13px' }}>
              Select a duplicate cluster from the table to inspect individual citizen submissions, AI confidence scores, and perform auto-merging.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default DuplicateAnalyzer;
